language: python
dist: xenial
jobs:
  include:
    - python: '3.6'
      script: pytest --cov=pysatMadrigal/
    - name: '3.7 with flake8'
      python: '3.7'
      script: pytest --flake8 --cov=pysatMadrigal/
    - python: '3.8'
      script: pytest --cov=pysatMadrigal/

services: xvfb
cache: pip

addons:
  apt:
    packages:
    - gfortran
    - libncurses5-dev

before_install:
  - python -m pip install --upgrade pip
  # Get the program and testing requirements
  - pip install -r test_requirements.txt
  - pip install -r requirements.txt
  # set up data directory
  - mkdir /home/travis/build/pysatData
  - python -c "import pysat; pysat.params['data_dirs'] = '/home/travis/build/pysatData'"
install:
  - python setup.py install

after_success:
 - coveralls --rcfile=setup.cfg
