language: python
dist: xenial
jobs:
  include:
    - python: '3.6'
      script: pytest --cov=pysatMadrigal/
    - name: '3.7 with flake8'
      python: '3.7'
      script: pytest --flake8 --cov=pysatMadrigal/
    - python: '3.8'
      script: pytest --cov=pysatMadrigal/

services: xvfb
cache: pip

addons:
  apt:
    packages:
    - gfortran
    - libncurses5-dev

install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes True --set changeps1 False
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  # Create conda test environment
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
  - conda activate test-environment
  - while read requirement; do conda install --yes $requirement; done < conda_requirements.txt
  # Conda does not provide (the correct versions of) all packages
  - pip install -r pip_requirements.txt
  # Custom pysat install, no longer needed after 3.0 release
  - cd ..
  - git clone --single-branch --branch v3-0-rc1 https://github.com/pysat/pysat.git
  - cd pysat
  # Install the pysat requirements
  - while read requirement; do conda install --yes $requirement; done < requirements.txt
  - python setup.py install
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
  # set up data directory
  - mkdir /home/travis/build/pysatData
  - cd ../pysatMadrigal
  # install pysatMadrigal
  - python setup.py install

after_success:
 - coveralls --rcfile=setup.cfg
